### PR TITLE
Remove default number of books to be processed from schedule

### PR DESCRIPTION
**Pull request by mjgiarlo**
## Why was this change made?

The default number of books to be processed is already set in [configuration](https://github.com/sul-dlss/google-books/blob/master/config/settings.yml#L2) and handled here: https://github.com/sul-dlss/google-books/blob/master/app/services/fetcher_service.rb#L51-L53

I'm not sure what this number is adding, especially since we're overriding this in shared_configs. And it's causing possibly confusing cron output like "Requesting processing of 2 of 10 books". "Why 2 of 10?", we may wonder when we've been away from the project a while.

## Was the documentation (README, DevOpsDocs, wiki) updated?

no.

### CODE REVIEW

**Comment by mjgiarlo** [comment]
I'd like @justinlittman to review this PR. I have a vague memory of discussing this, or a related change, a number of weeks ago and perhaps I didn't/don't grok this.

**Comment by justinlittman** [comment]
I'm fairly sure that number if required. In this case, it means that up to 10 books can be requested for processing. (There is a separate configuration that says the number of concurrent books that we should keep in the processing queue, which is currently 2.)

**Comment by mjgiarlo** [comment]
@justinlittman You're right, it is required. I'll pull this branch down and take another hack at it, mebbe.

**Comment by mjgiarlo** [comment]
@justinlittman Take two: https://github.com/sul-dlss/google-books/pull/330/files

**Pull request merged**
