### PR TITLE
Fix to invoking all in schedule.

### PR DESCRIPTION
**Pull request by justinlittman**
## Why was this change made?
Invoking the all rake task requires providing the max number of books to request.

## Was the documentation (README, DevOpsDocs, wiki) updated?
No.

### CODE REVIEW

**Comment by justinlittman** [comment]
I'm not following. Where is the 10 knowledge in multiple places?

**Comment by mjgiarlo** [comment]
@justinlittman I was thinking of this config value:

https://github.com/sul-dlss/google-books/blob/master/config/settings.yml#L2

Which is used here:

https://github.com/sul-dlss/google-books/blob/master/app/services/fetcher_service.rb#L45

But we could use it as the default value in the rake task itself.

**Comment by justinlittman** [comment]
In my view, these two different things. One is up to how many books should be processing at a time. The other is up to how many books do I want to request at this time.

**Comment by mjgiarlo** [comment]
@justinlittman OK, I buy it.

**Pull request merged**
